"""empty message

Revision ID: 6b932d46c4dc
Revises: 
Create Date: 2019-01-21 11:14:43.030252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b932d46c4dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxies',
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('port_number', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('response_time', sa.Integer(), nullable=False),
    sa.Column('proxy_type', sa.String(), nullable=False),
    sa.Column('anonymity', sa.String(), nullable=False),
    sa.Column('last_check', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('ip_address', 'port_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proxies')
    # ### end Alembic commands ###
